[package]
name = "dness"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[dependencies]
trust-dns-resolver = "0.10"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
structopt = "0.2.14"
failure = "0.1.3"
chrono = "0.4"

[dependencies.log]
version = "0.4"
features = ["serde"]

# Disable logging timestamp info (ie: the humantime feature) as mechanisms like
# systemd / journald will show the timestamp that received the log line at.
# Ideally, log formatting should be configurable, but this is a good first step
[dependencies.env_logger]
version = "0.6"
default-features = false
features = ["termcolor", "atty", "regex"]
